### ISSUE TITLE
Intersected gists, removed gists

### ISSUE THREAD

**Issue by timqzm** [loov/gistsnip#1]
Hello @egonelbre and thanks for your tool!

Just 2 ideas to improve it:

1. Remove `//gistsnip:` comments in gists.
I've tried intersected gists:
```
class ManagerAssembly: Assembly {
    //gistsnip:start:gist1
    func assemble(container: Container) {
        //gistsnip:start:gist2
        //gistsnip:start:gist3
        container.autoregister(ChildManagering.self, initializer: ChildManager.init)
        //gistsnip:end:gist2
            .inObjectScope(.container)
        //gistsnip:end:gist1
        container.autoregister(UserManagering.self, initializer: UserManager.init)
            .inObjectScope(.container)
    }
    //gistsnip:end:gist3
}
```
It works as designed, but doesn't hide comments:
<img width="748" alt="Screenshot 2019-12-15 at 22 58 07" src="https://user-images.githubusercontent.com/13407092/70869265-dc011980-1f91-11ea-9659-b1978a1b4da1.png">

2. Track deleted gists. I removed `//gistsnip:start:gist2` and `//gistsnip:end:gist2`, run `gistsnip`, but gist2 still lives in `.gistsnip` file.

P.S. Also I mentioned you have a cool link in a description in your auto-generated [gist](https://gist.github.com/egonelbre/a2a3c3b84b15326e61b5696995d24891), but my gists don't have descriptions. Did you add links manually?

**Comment by timqzm** [comment]
I'm ready to help somehow, but I didn't write a line of Go before 😄

**Comment by egonelbre** [comment]
The link description should appear automatically, however you should remember to commit before running `gistsnip`, otherwise it won't know the final link to the file.

**Comment by egonelbre** [comment]
The reason I'm not removing/deleting old gists is because you might later reintroduce them in another commit. I'm not sure what the right approach for them would be.

**Comment by timqzm** [comment]
Thank you very much for nested stuff! Works good! But before that I've tried deleting:

1. I recreated `gist2` in a few lines below. But instead of updating old gist, the tool created a new one with the same name:

<img width="751" alt="Screenshot 2019-12-16 at 14 12 03" src="https://user-images.githubusercontent.com/13407092/70907730-4b1e5280-2012-11ea-99bd-6aba6f418877.png">

2. Before doing that, I pushed all changes to master, but new gist2 doesn't have description link anyway 😢

3. Every gist has empty line at the bottom, I guess it's a bug

4. What do you think about adding repo name in gist names? It would be cool imho

**Comment by timqzm** [comment]
I don't really care about deleting stuff, just FYI 😉 I can manually delete some gists and edit `.gistnip` in this case

**Comment by egonelbre** [comment]
1. Realized that people also use `https://github.com/a/b` as the repository URL, so it wasn't able to figure out the actual link.
2. Fixed the empty thing lines thing.
3. Also fixed dedenting code with spaces.

Whether it creates or updates existing gist depends entirely on the `.gistsnip` file. If the gist with appropriate ID / URL is missing then it will create a new one.

**Comment by timqzm** [comment]
You rock! Thanks for so quick support!

**Comment by timqzm** [comment]
@egonelbre sorry for pinging 😉
> What do you think about adding repo name in gist names?

**Comment by egonelbre** [comment]
Do you have any specific way that the message should look like?

**Comment by egonelbre** [comment]
Also, please make a separate issue for it, so it's easier to track.

**Comment by timqzm** [comment]
> Do you have any specific way that the message should look like?

I mean naming gists `db-demo\03_server\main#main.go` instead of `03_server\main#main.go`

> Also, please make a separate issue for it, so it's easier to track.

No problem! Do you think it's a good idea, about naming? If so I'll create an issue

**Comment by egonelbre** [comment]
@timqzm Yeah, but I'm not sure what the exact solution will be... I'm still thinking whether it should be customizable together with the description or not (e.g. via a template parameter)
