### ISSUE TITLE
Include repo name in gist names

### ISSUE THREAD

**Issue by timqzm** [loov/gistsnip#2]
To have gists like `db-demo\03_server\main#main.go` instead of `03_server\main#main.go`
Is it possible to implement?

Motivation: I can have many gists `main#main.go` from different repos. Having a repo name in a gist name makes it clearer.

P.S.: However, [some people](https://gist.github.com/onmyway133) don't care about it at all 🙃

**Comment by egonelbre** [comment]
It now includes the repository link by default, but you can manually modify the description if you wish.

`gistsnip -description "my super awesome example {{.RepositoryLink}}"`
